// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIxOaAzlYnMHVLjGAEtqGYYYr7zW0VTfI',
    appId: '1:600995924113:web:67e98385f283741458d730',
    messagingSenderId: '600995924113',
    projectId: 'flutterapp-eaaf3',
    authDomain: 'flutterapp-eaaf3.firebaseapp.com',
    databaseURL: 'https://flutterapp-eaaf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-eaaf3.appspot.com',
    measurementId: 'G-ZDDJNF2VV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD6g8WWhdMluhT6JdmvI88XIWxjn0SGbQ',
    appId: '1:600995924113:android:eac07a99c7a3311258d730',
    messagingSenderId: '600995924113',
    projectId: 'flutterapp-eaaf3',
    databaseURL: 'https://flutterapp-eaaf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-eaaf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE6VMYKh7MzJwQqjsod11WGlDgigG5xUM',
    appId: '1:600995924113:ios:dbfea1fa4d3d410e58d730',
    messagingSenderId: '600995924113',
    projectId: 'flutterapp-eaaf3',
    databaseURL: 'https://flutterapp-eaaf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-eaaf3.appspot.com',
    androidClientId: '600995924113-1l034teshpfnhhunup36duc342q86b9h.apps.googleusercontent.com',
    iosClientId: '600995924113-bk1fmngbl6gf8kk2r1u6lkhepis0g1j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPython.RunnerTests',
  );

}